version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  app:
    # build: .
    image: openai-api-proxy:latest
    ports:
      - "9000:9000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
